HR/urls.py
from django.urls import path
from . import views
from . import api

urlpatterns = [
    
    path('hr/',views.hr,name='hr'),
    path('',views.hrHome,name='hrHome'),

    path('dept/', views.dept, name = 'dept'),
    path('dept/<pk>/', views.deptinfo, name = 'deptinfo'),
    path('create_department/', views.createdept, name = 'createdept'),
    path('update_department/<pk>/',views.updatedept,name='update_dept'),
    path('delete_dept/<pk>/',views.deleteDept,name='delete_dept'),
   


    path('staff/', views.staff, name = 'staff'),
    path('staff/<pk>/', views.staffinfo, name = 'staffinfo'),
    path('create_staff/', views.createstaff, name = 'createstaff'),
    path('update_staff/<pk>/',views.updatestaff,name='update_staff'),
    path('delete_staff/<pk>/',views.deleteStaff,name='delete_staff'),

]

authentication/api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from . import views
# app_name = 'authentication'

urlpatterns = [
    #custom auth api
    # path('',views.AuthAPI.as_view()),  
    # JWT
    #path('jwt/',obtain_jwt_token),
   # path('jwt/refresh/',refresh_jwt_token),
    
    #path('register/',views.RegistrationAPIView.as_view(),name = 'register'),
    #path('login/',views.LoginAPIView.as_view()),

    #path('user/',views.UserListCreateView.as_view(),name = 'user'),
    #path('user/<pk>/',views.UserDetailView.as_view(),name = 'user-del'),

    path('com/',views.CompanyListCreateView.as_view(),name = 'company'),
    path('com/<pk>/',views.CompanyDetailView.as_view(),name = 'company-del'),

    path('emp/',views.EmployeeListCreateView.as_view(),name = 'employee'),
    path('emp/<pk>/',views.EmployeeDetailView.as_view(),name = 'employee-del'),

    path('cus/',views.CustomerListCreateView.as_view(),name = 'customer'),
    path('cus/<pk>/',views.CustomerDetailView.as_view(),name = 'customer-del'),

    path('ven/',views.VendorListCreateView.as_view(),name = 'vendor'),
    path('ven/<pk>/',views.VendorDetailView.as_view(),name = 'vendor-del'),
]


# from .views import CustomerViewSet
# from rest_framework.routers import DefaultRouter

# router = DefaultRouter()
# router.register(r'', CustomerViewSet, basename='user')
# urlpatterns = router.urls
# 88

authentication/urls.py
from django.urls import path
from . import views
from .api import *
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    
    
    path('',views.profile,name = 'profile'),

    # sa30 Api
    path('registerApi/',views.RegisterApiView.as_view()),
    path('registerApi/<int:pk>',views.UD_RegisterApiView.as_view()),
    path('loginApi/',views.LoginWithTokenAuthenticationAPIView.as_view()),
    path('positionApi/',views.PositionApiView.as_view()),
    path('positionApi/<int:pk>',views.UD_PositionApiView.as_view()),
    path('departmentApi/',views.DepartmentApiView.as_view()),
    path('departmentApi/<int:pk>',views.UD_DepartmentApiView.as_view()),
    path('businessApi/',views.BusinessApiView.as_view()),
    path('businessApi/<int:pk>',views.UD_BusinessApiView.as_view()),
    path('customerApi/',views.CustomerApiView.as_view()),
    path('customerApi/<int:pk>',views.UD_CustomerApiView.as_view()),
    #sa30 
    path('addcustomernew/',views.customernew_view,name="addcustomernew"),
    path('updatecustomernew/<int:id>',views.customernewupdate,name="customernewupdate"),
    path('deletecustomernew/<int:id>',views.customernewdelete_view,name="customernewdelete"),
    path('addvendornew/',views.vendornew_view,name="addvendornew"),
    path('updatevendornew/<int:id>',views.vendornewupdate,name="vendornewupdate"),
    path('deletevendornew/<int:id>',views.vendornewdelete_view,name="vendornewdelete"),

    path('register/',views.registraiton_view,name="register"),
    path('userupdate1/<int:id>',views.userupdate1,name="userupdate"),
    path('position/',views.position_view,name="position"),
    path('positiondelete/<int:id>',views.positiondelete_view,name="positiondelete"),
    path('positionupdate/<int:id>',views.positionupdate,name="positionupdate"),
    path('department/',views.department_view,name="department"),
    path('departmentdelete/<int:id>',views.departmentdelete_view,name="departmentdelete"),
    path('departmentupdate/<int:id>',views.departmentupdate,name="departmentupdate"),
    path('business/',views.business_view,name="business"),
    path('businessdelete/<int:id>',views.businessdelete_view,name="businessdelete"),
    path('businessupdate/<int:id>',views.businessupdate,name="businessupdate"),
    path('login/',views.userLogin_view,name="userlogin"),
    path('logout/',views.userLogout_view,name="userlogout"),
    path('dashboard/',views.userdashboard_view,name="userdashboard"),
    path('addcompany/',views.addcompany,name="addcompany"),
    path('company/<int:pk>',views.compinfo,name="companyinfo"),
    path('companyupdate/<int:id>',views.compupdate,name="companyupdate"),
    path('companydelete/<int:id>',views.compdelete,name="companydelete"),
    path('contactperson/<int:id>',views.contactperson_view,name="contactperson"),
    path('addcontactperson/',views.addcontactperson,name="addcontactperson"),
    path('contactpersonupdate/<int:id>',views.contactpersonupdate,name="contactpersonupdate"),
    path('contactpersondelete/<int:id>',views.contactpersondelete,name="contactpersondelete"),
    path('contactpersonApi/',views.ContactpersonApiView.as_view()),
    path('contactpersonApi/<int:pk>',views.UD_ContactpersonApiView.as_view()),
    path('calenderview/',views.calenderview,name="calenderview"),
    path('userScorecard/',views.userScorecard,name="userScorecard"),

    


    
    # authentication/
    path('user/', views.indexview.as_view(), name = 'user'),

    path('customer/', views.customer, name = 'customers'),
    path('customer/<pk>/', views.customerinfo, name = 'customerinfo'),
    path('customerdelete/<id>/', views.customerdelete_view, name = 'customerdelete'),
    path('customerdetail/<id>/', views.customerdetail, name = 'customerdetail'),


    path('company/', views.company, name = 'company'),
    path('company/<pk>/', views.compinfo, name = 'compinfo'),
    path('companyApi/',views.CompanyApiView.as_view()),
    path('companyApi/<int:pk>',views.UD_CompanyApiView.as_view()),

    path('employee/', views.employee, name = 'employee'),
    path('employee/<pk>', views.empinfo, name = 'empinfo'),

    path('vendor/', views.vendor, name = 'vendor'),
    path('vendor/<pk>', views.vendinfo, name = 'vendinfo'),


    
    # path('register/', views.register, name='sign-up'),
    # path('login/', views.login, name='sign-in'),


]
    
    
 

crm/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    
    path('admin/', admin.site.urls),   
    path('auth/',include('authentication.urls')),
    path('projectmanagement/',include('ProjectManagement.urls')),
    #templates urls
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    # path('',views.home,name='home'),
    # path('profile/', include('authentication.urls')),  
    path('finance/',include('finance.urls')),
    #path('project/',include('ProjectManagement.urls')),
    path('hr/',include('HR.urls')),
    path('payroll/',include('payroll.urls')),
    #path('sla/',include('ServiceLevelAgreement.urls')),
    path('service/',include('services.urls')), 
    path('production/',include('production.urls')), 
   
    
    # apis urls 
    path('api/auth/',include('authentication.Newapi.urls')),
    path('api/auth2/',include('authentication.api.urls')),
    path('api/finance/',include('finance.api.urls')),
    path('api/hr/',include('HR.api.urls')),
    path('api/payroll/',include('payroll.api.urls')),  
    path('api/services/',include('services.api.urls')), 
    path('api/pm/',include('ProjectManagement.urls')),
    path('api/sla/',include('ServiceLevelAgreement.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HR/models.py
from django.db import models
from authentication.models import EmployeeProfile
from payroll.models import EmployeePackage

GENDER_CHOICES = (
    ('Not Known', 'NOT_KNOWN'),
    ('Male', 'MALE'),
    ('Female', 'FEMALE')
)


class Department(models.Model):
    deptId        = models.CharField(max_length=10)
    dept_name     = models.CharField(max_length=20)  # abc / xyz etc.
    branch        = models.CharField(max_length=20)  # location :- chandigarh/pune/banglore etc.

    def __str__(self):
        return self.dept_name
    
    class Meta:
        verbose_name_plural = 'department'
   


class StaffProfile(models.Model):  # dynamic
    EmpId                     = models.ForeignKey(EmployeeProfile,on_delete=models.CASCADE,null=True)
    department                = models.ForeignKey(Department, on_delete=models.CASCADE,null=True)
    packageId                 = models.ForeignKey(EmployeePackage, models.CASCADE,editable = False,null=True)
    
    # leave_days             = models.PositiveIntegerField()
    # sick_days              = models.PositiveIntegerField()
    no_of_holidays_allowed    = models.IntegerField()
    salary_package                   = models.IntegerField()
    Joining_date              = models.DateField(null=True)
    description               = models.TextField(blank=True, default='')
    # end_date               = models.DateField(null=True)  # on contract basis : bond duration
    isactive                  = models.BooleanField(default=False)

    def __str__(self):
        return self.EmpId.first_name

    class Meta:
        verbose_name_plural = 'staffProfile'

    

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *
from django.contrib.auth import authenticate


class RegistratinForm(UserCreationForm):
	email=forms.EmailField(max_length=50,help_text='Required. Add a valid email address')
	first_name=forms.CharField(max_length=50)
	class Meta:
		model=User
		fields=("email","first_name","password1","password2",
			'company_create_permission','company_read_permission','company_edit_permission','company_delete_permission',
			'contactperson_create_permission','contactperson_read_permission','contactperson_edit_permission','contactperson_delete_permission',
			'project_create_permission','project_read_permission','project_edit_permission','project_delete_permission','position','department','is_admin')

class userupdateform(forms.ModelForm):
	class Meta:
		model=User
		fields='__all__'
		exclude=['password','is_superuser','is_active','is_staff']
#		fields=("email","first_name",
#                        'company_create_permission','company_read_permission','company_edit_permission','company_delete_permission',
#                        'contactperson_create_permission','contactperson_read_permission','contactperson_edit_permission','contactperson_delete_permission',
#                        'project_create_permission','project_read_permission','project_edit_permission','project_delete_permission','position','department','is_admin')



class UserLoginForm(forms.ModelForm):
	password=forms.CharField(label='Password',widget=forms.PasswordInput)

	class Meta:
		model=User
		fields=('email','password')

	def clean(self):
		if self.is_valid():
			email=self.cleaned_data['email']
			password=self.cleaned_data['password']
			if not authenticate(email=email,password=password):
				raise forms.ValidationError("Invalid Creadentials")


class CompanyCreationForm(forms.ModelForm):
	class Meta:
		model=Company
		fields='__all__'

class PositionForm(forms.ModelForm):
	class Meta:
		model=Position
		fields='__all__'

class ContactPersonCreationForm(forms.ModelForm):
	class Meta:
		model=ContactPerson
		fields='__all__'

class DepartmentForm(forms.ModelForm):
	class Meta:
		model=Department
		fields='__all__'

class BusinessForm(forms.ModelForm):
	class Meta:
		model=Business
		fields='__all__'

class CustomerNewForm(forms.ModelForm):
	class Meta:
		model=CustomerNew
		fields=['company_name']

class VendorNewForm(forms.ModelForm):
	class Meta:
		model=VendorNew
		fields=['company_name']

class CustomerForm(forms.ModelForm):
	class Meta:
		model=Customer
		fields=['first_name','last_name','email_id','contact','address_1','city','state','country','zip_code','customer_id']

# class CustomUserCreationForm(UserCreationForm):

#     class Meta:
#         model = User
#         fields = ('username', 'email','password1','password2')

# class CustomUserChangeForm(UserChangeForm):

#     class Meta:
#         model = User
#         fields = UserChangeForm.Meta.fields


            
        
            
        

authentication/Newapi/views.py
import jwt
from django.conf import settings
from django.contrib import messages
from django.forms.models import model_to_dict
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from rest_framework import authentication
from rest_framework import permissions,authentication
from rest_framework import generics,mixins
from rest_framework import (
    generics,
    status,
)
from .serializer import *
from rest_framework.exceptions import NotFound
from rest_framework.permissions import (IsAuthenticated,
                                        IsAuthenticatedOrReadOnly)
from rest_framework.response import Response
from rest_framework.views import APIView
# from authentication.models import (User, UserProfile, UserDevices)
from authentication.models import (User)
# from authentication.permissions import (
#     IsClientAdmin,
#     IsProfileOwner,
#     IsOwnerOrAdmin)
from authentication.renderer import UserJSONRenderer, ClientJSONRenderer
from django.core.exceptions import ObjectDoesNotExist
from .serializer import (RegistrationSerializer, LoginSerializer)
from django.core.cache import cache

# from utils import BaseUtils
from utils.permissions import IsViewerOrReadOnly, IsReviewer, IsAdmin
# from utils.emailer import Emailer
from utils.util import generateOTP
# from utils.models import BaseAbstractModel


class RegistrationAPIView(generics.GenericAPIView):
    """Register new users."""
    serializer_class = RegistrationSerializer
    renderer_classes = (UserJSONRenderer,)

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        user_data = serializer.data
        message = [
            request,
            user_data["email"]
        ]

        response = {
            "data": {
                "user": dict(user_data),
                "message": "Account created successfully",
                "status": "success"
            }
        }
        return Response(response, status=status.HTTP_201_CREATED)

class LoginAPIView(generics.GenericAPIView):
    """login a user via email"""
    serializer_class = LoginSerializer
    renderer_classes = (UserJSONRenderer,)

    def post(self, request):
        print('now here', request.data)
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        user_data = serializer.data
        response = {
            "data": {
                "user": dict(user_data),
                "message": "You have successfully logged in",
                "status": "success"
            }
        }
        return Response(response, status=status.HTTP_200_OK)



class UserListCreateView(mixins.ListModelMixin,
                        mixins.CreateModelMixin,
                        generics.GenericAPIView):
    queryset                = User.objects.all()
    serializer_class        = UserSerializer
    permission_classes      =  []
    # authentication_classes  =  [SessionAuthentication]
    lookup_field = 'pk'

    def get(self,request,*args,**kwargs):
        return  self.list(request,*args,**kwargs)

    def post(self,request,*args,**kwargs):
        return self.create(request,*args,**kwargs)

    # def perform_create(self,serializer):
    #     user    = self.request.user
    #     serializer.save(user=user)

class UserDetailView(mixins.RetrieveModelMixin,
                    mixins.UpdateModelMixin,
                    mixins.DestroyModelMixin,
                    generics.GenericAPIView):
    queryset                = User.objects.all()
    serializer_class        = UserSerializer
    permission_classes      = []
    # authentication_classes  = [SessionAuthentication]
    lookup_field            = 'pk'

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

authentication/templates/authentication/addcompany.html
{% extends "crm/base.html" %}
{% load static %}
{% load bootstrap %}
{% comment %} {% bootstrap_css %}         {# Embeds Bootstrap CSS #} {% endcomment %}
{% comment %} {% bootstrap_javascript jquery='full' %} {% endcomment %}

{% block extrahead %}       {# Extra Resources Start #}
{{ form.media }}            {# Form required JS and CSS #}
{% endblock %} 

{% block content %}




<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="">
      <h5 class="display-5 heading my-3 py-2 px-2">Add Company</h5>

                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <hr>
                    <div class="overflow-auto">
                        <div class="form-inline">
                            <div class="form-group">
                                {# {{ent_form|bootstrap_horizontal:'col-lg-4'}}  #}
                            </div>
                        </div>
                    </div>
                    
                    <hr>
                    <div class="">
                        <input class="btn btn-primary" type="submit" name="Submit">
                    </div>
                    <hr>
                </form>
    
            </div>
        </div>
     <div class="col-6">
                <h1 class="display-5 ">Company</h1>
               <table class="table">
     <thead>
       <tr>
         <th scope="col"></th>
       </tr>
     </thead>
     <tbody>
     
         {% for item in company  %}
             <tr>
         <td>{{item.company_Name}} 
        <a href="{% url "companydelete" item.id %}" class="btn btn-danger float-end">Delete</a>
        <a href="{% url "companyupdate" item.id %}" class="btn btn-primary float-end mx-2">Update</a>
   
         </td>
         
       </tr>
         {% endfor %}
   
      
     </tbody>
   </table>
        </div>
    </div>
</div>


{% endblock %}

authentication/templates/authentication/addcustomernew.html
{% extends "crm/base.html" %}
{% load static %}
{% load bootstrap %}
{% comment %} {% bootstrap_css %}         {# Embeds Bootstrap CSS #} {% endcomment %}
{% comment %} {% bootstrap_javascript jquery='full' %} {% endcomment %}

{% block extrahead %}       {# Extra Resources Start #}
{{ form.media }}            {# Form required JS and CSS #}
{% endblock %} 

{% block content %}




<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="">
      <h5 class="display-5 heading my-3 py-2 px-2">Add Customer</h5>

                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <hr>
                    <div class="overflow-auto">
                        <div class="form-inline">
                            <div class="form-group">
                                {# {{ent_form|bootstrap_horizontal:'col-lg-4'}}  #}
                            </div>
                        </div>
                    </div>
                    
                    <hr>
                    <div class="">
                        <input class="btn btn-primary" type="submit" name="Submit">
                    </div>
                    <hr>
                </form>
    
            </div>
            <div class="col-6">
                <h1 class="display-5 ">Customer</h1>
               <table class="table">
     <thead>
       <tr>
         <th scope="col"></th>
       </tr>
     </thead>
     <tbody>
     
         {% for item in customer  %}
             <tr>
         <td>{{item.company_name}} 
        <a href="{% url "customernewdelete" item.id %}" class="btn btn-danger float-end">Delete</a>
        <a href="{% url "customernewupdate" item.id %}" class="btn btn-primary float-end mx-2">Update</a>
   
         </td>
         
       </tr>
         {% endfor %}
   
      
     </tbody>
   </table>
        </div>
    </div>
</div>


{% endblock %}

authentication/templates/authentication/registration.html
{% extends "crm/base.html" %}
{% load static %}
{% load bootstrap %}

{% block title %}
SignUp
{% endblock title %}
{% block content %}
 <style >

  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {a
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="text"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#id_position{
  padding: 10px;
  margin-bottom:5px;
  min-width: 48vh
}
#id_create_entry{
  padding: 10px;
  margin-bottom:5px;
 min-width: 48vh
}
#id_read_entries{
  padding: 10px;
  margin-bottom:5px;

}
#id_edit_entry{
  padding: 10px;
  margin-bottom:5px;
 min-width: 48vh
}
#id_delete_entry{
  padding: 10px;
  margin-bottom:5px;
 min-width: 48vh
}

.rowdir{
    
}

#id_position{
  max-width:250px;
  min-width: 250px;

}
#id_department{
  max-width:250px;
  min-width: 250px;
  padding: 10px;
}
 </style>
 <div class="container">
   <div class="row">
     <div class="col-5">
        <h1 class="display-4">Add Account</h1>
<form method="POST">
    {% csrf_token %}


      <main class="form-signin ">

        <div class="form-floating">
      <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>

        <div class="form-floating">
      <input type="text" name="first_name" class="form-control" id="floatingInput" placeholder="Firstname">
      <label for="floatingInput">FullName</label>
    </div>

    <div class="form-floating">
      <input type="password" name="password1" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div> 

    <div class="form-floating">
      <input type="password" name="password2" class="form-control" id="floatingPassword" placeholder="Repeat Password">
      <label for="floatingPassword">Repeat Password</label>
    </div>

      <div class="form-floating py-2 my-2">

    <strong>  <label class="form-check-label" for="flexCheckDefault">
   Position
     </label></strong>
      {{form.position}}
    </div>  


        <div class="form-floating py-2 my-2">

    <strong>  <label class="form-check-label" for="flexCheckDefault">
   Department
     </label></strong>

      {{form.department}}

    </div>

 <strong>  <label class="form-check-label" for="flexCheckDefault">
   Admin
     </label></strong>

<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="true" name="is_admin">
  <label class="form-check-label" for="inlineCheckbox1">Yes</label>
</div>

    <strong>  <label class="form-check-label" for="flexCheckDefault">
   Company related permissions:
     </label></strong>

<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="true" name="company_read_permission">
  <label class="form-check-label" for="inlineCheckbox1">Read</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="true" name="company_create_permission">
  <label class="form-check-label" for="inlineCheckbox2">Create</label>
</div><br>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="true" name="company_edit_permission" >
  <label class="form-check-label" for="inlineCheckbox3">Edit </label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="true" name="company_delete_permission">
  <label class="form-check-label" for="inlineCheckbox3">Delete </label>
</div>


    <strong>  <label class="form-check-label" for="flexCheckDefault">
   Project related permissions:
     </label></strong><br>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="true" name="project_read_permission">
  <label class="form-check-label" for="inlineCheckbox1">Read</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="true" name="project_create_permission">
  <label class="form-check-label" for="inlineCheckbox2">Create</label>
</div><br>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="true" name="project_edit_permission">
  <label class="form-check-label" for="inlineCheckbox3">Edit </label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="true" name="project_delete_permission" >
  <label class="form-check-label" for="inlineCheckbox3">Delete </label>
</div>


    <strong>  <label class="form-check-label" for="flexCheckDefault">
   Contact Person related permissions:
     </label></strong><br>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="true" name="contactperson_read_permission">
  <label class="form-check-label" for="inlineCheckbox1">Read</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="true" name="contactperson_create_permission">
  <label class="form-check-label" for="inlineCheckbox2">Create</label>
</div><br>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="true" name="contactperson_edit_permission">
  <label class="form-check-label" for="inlineCheckbox3">Edit </label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="true" name="contactperson_delete_permission" >
  <label class="form-check-label" for="inlineCheckbox3">Delete </label>
</div>

   

    {% for field in form %}
      <p>

        {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
        {% endfor %}
        </p>

        {% if form.non_field_errors %}
            <div style="color:red;">
              <p>{{form.non_field_errors}}</p>
            </div>
        {% endif %}

      
    {% endfor %}

    <button class="w-100 btn btn-lg btn-primary" type="submit">SignUp</button>
</main>



    
  </form>
     </div>
          <div class="col-6">
             <h1 class="display-3 ">Accounts</h1>
            <table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Position</th>
      <th scope="col">Department</th>
    </tr>
  </thead>
  <tbody>
  
      {% for item in accounts  %}
          <tr>
      <td>{{item.firstname}}</td>
      <td>{{item.email}}</td>
      <td>{{item.position}}</td>
      <td>{{item.department}}</td>
	<td><a  href="{% url "userupdate" item.id %}" class="btn btn-primary float-end ">Update</a>
	</td>
    </tr>
      {% endfor %}

   
  </tbody>
</table>
</div>
   </div>
 </div>
 
{% endblock content %}