HR/urls.py
from django.urls import path
from . import views
from . import api

urlpatterns = [
    
    path('hr/',views.hr,name='hr'),
    path('',views.hrHome,name='hrHome'),

    path('dept/', views.dept, name = 'dept'),
    path('dept/<pk>/', views.deptinfo, name = 'deptinfo'),
    path('create_department/', views.createdept, name = 'createdept'),
    path('update_department/<pk>/',views.updatedept,name='update_dept'),
    path('delete_dept/<pk>/',views.deleteDept,name='delete_dept'),
   


    path('staff/', views.staff, name = 'staff'),
    path('staff/<pk>/', views.staffinfo, name = 'staffinfo'),
    path('create_staff/', views.createstaff, name = 'createstaff'),
    path('update_staff/<pk>/',views.updatestaff,name='update_staff'),
    path('delete_staff/<pk>/',views.deleteStaff,name='delete_staff'),

]

ProjectManagement/urls.py
from django.urls import path
from . import views

urlpatterns = [

		#sa30
		path('projectAPI/',views.CR_ProjectApiView.as_view()),
        path('projectAPI/<int:pk>',views.U_ProjectApiView.as_view()),
        path('teamAPI/',views.CR_TeamApiView.as_view()),
        path('teamAPI/<int:pk>',views.U_TeamApiView.as_view()),
        path('teamMemberAPI/',views.CR_TeamMemberApiView.as_view()),
        path('teamMemberAPI/<int:pk>',views.U_TeamMemberApiView.as_view()),
        path('tasksAPI/',views.CR_Tasks.as_view()),
        path('tasksAPI/<int:pk>',views.U_Tasks.as_view()),

        path('home/',views.home2,name='projectmanagementHome'),
        path('project/',views.project_view,name='project'),
        path('totalproject/',views.totalproject_view,name='totalproject'),
        path('inprogressproject/',views.inprogressproject_view,name='inprogressproject'),
        path('completedproject/',views.completedproject_view,name='completedproject'),
        path('projectupdate/<int:id>/',views.projectUpdate_view,name='projectupdate'),
        path('projectdelete/<int:id>/',views.projectDelete_view,name='projectdelete'),
        path('projectinfo/<int:id>/',views.projectInfo_view,name='projectinfo'),
        # path('<int:id>/',views.projectUpdate_view,name='projectupdate'),
        path('team/',views.team_view,name='team'),
        path('teamView/',views.teamView_view,name='teamView'),
        path('teamupdate/<int:id>/',views.teamUpdate_view,name='teamupdate'),
        path('teamdelete/<int:id>/',views.teamDelete_view,name='teamdelete'),

        path('teamember/',views.teammember_view,name='teammember'),
        path('teamemberView/',views.teammemberView_view,name='teammemberview'),
        path('teammemberUpdate/<int:id>/',views.teammemberUpdate_view,name='teammemberupdate'),
        path('teammemberdelete/<int:id>/',views.teammemberDelete_view,name='teammemberdelete'),

        path('task/',views.tasks_view,name='task'),
        path('addtaskinfopage/<str:membername>/<str:teamname>',views.addTaskInfoPage,name='addtaskinfopage'),
        path('taskView/',views.tasksView_view,name='taskView'),
        path('taskView/<str:projectname>',views.singletask_view,name='singletask'),
        path('singletaskstatus/<int:id>/',views.singletaskstatus,name='singletaskstatus'),
        path('taskUpdate/<int:id>/',views.taskUpdate_view,name='taskupdate'),
        path('taskdelete/<int:id>/',views.tasksDelete_view,name='taskdelete'),
        path('taskprogress/',views.taskprogressView_view,name='taskprogress'),
        path('taskprogressUpdate/<int:id>/',views.taskprogressUpdate_view,name='taskprogressupdate'),




        # path('mail',views.index),

         path('BO/',views.BOListView.as_view(),name='details'),
        path('BO/<pk>/',views.BOView.as_view(),name='put'),
         path('Project/',views.ProjectListView.as_view(),name='details'),
        path('Project/<pk>/',views.ProjectView.as_view(),name='put'),
         #path('Team/',views.TeamListView.as_view(),name='details'),

    # path('Team/<name>/edit/',views.TeamUpdateAPIView.as_view(),name='put'),

        #path('',views.ProjectManagement,name='project')
        
]

crm/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    
    path('admin/', admin.site.urls),   
    path('auth/',include('authentication.urls')),
    path('projectmanagement/',include('ProjectManagement.urls')),
    #templates urls
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    # path('',views.home,name='home'),
    # path('profile/', include('authentication.urls')),  
    path('finance/',include('finance.urls')),
    #path('project/',include('ProjectManagement.urls')),
    path('hr/',include('HR.urls')),
    path('payroll/',include('payroll.urls')),
    #path('sla/',include('ServiceLevelAgreement.urls')),
    path('service/',include('services.urls')), 
    path('production/',include('production.urls')), 
   
    
    # apis urls 
    path('api/auth/',include('authentication.Newapi.urls')),
    path('api/auth2/',include('authentication.api.urls')),
    path('api/finance/',include('finance.api.urls')),
    path('api/hr/',include('HR.api.urls')),
    path('api/payroll/',include('payroll.api.urls')),  
    path('api/services/',include('services.api.urls')), 
    path('api/pm/',include('ProjectManagement.urls')),
    path('api/sla/',include('ServiceLevelAgreement.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectManagement/models.py
from django.db import models
from django.forms import fields
from django.contrib.auth.models import AbstractUser
from authentication.models import *
import nested_admin
from authentication.models import *
import datetime
stage=[ ('PLANNING','Planning'), ('DEVELOPMENT','Development'),('TESTING','Testing'),
              ('DEPLOYMENT','Deployment'),('COMPLETED','Completed')]

complete_or_Inprogress_choice=[('inprogress','INPROGRESS'),('completed','COMPLETED')]
update=[('allocated','Allocated'),('completed','COMPLETED'),('error','ERROR')]

class Businessopportunity(models.Model):

       project_name       = models.CharField(max_length=100,blank=False,null=False,default='')
       description        = models.TextField(max_length=300,blank=False,null=False)
       company_name       = models.CharField(max_length=100, blank=False, null=False)
       address            = models.CharField(max_length=100, default='')
       contact_person     = models.CharField(max_length=100, blank=False, null=False,default='')
       email_id           = models.EmailField(max_length=100, blank=False, null=False,default='')
       phone_no           = models.CharField(max_length=100,blank=False,null=False,default='')
       additional_contact = models.CharField(max_length=300,blank=False,null='False',default='')
       details            = models.CharField(verbose_name='',max_length=300,blank=False,null='False')
       start_date         = models.DateField()
       deadline           = models.DateField()
       responsible_person = models.ManyToManyField(EmployeeProfile)
       followup_date      = models.DateField()
       followup_message   = models.TextField(max_length=150,default='')
       upload_documents   = models.FileField(blank=True)

       class Meta():
              verbose_name_plural='Business Opportunity'

       def __str__(self):
              return self.company_name

# sa30

# class ProjectDetail(models.Model):
#        project_name=models.CharField(max_length=100,blank=False,null=False)
#        description=models.TextField(max_length=1000, blank=True, null=True)
#        start_date=models.DateField(blank=True)
#        project_deadline=models.DateField(blank=True)
#        company_name=models.CharField(max_length=100,blank=False,null=False)
#        contact_person=models.CharField(max_length=100,blank=True,null=True)
#        project_status=models.CharField(choices=stage, max_length=200, blank=False, null=False)
#        project_complete_or_Inprogress=models.CharField(max_length=20,blank=False,null=False,choices=complete_or_Inprogress_choice)         


# class ProjectTeam(models.Model):
#        project=models.OneToOneField(ProjectDetail,on_delete=models.CASCADE,primary_key=True)
#        project_manager=models.CharField(max_length=50)




# # sa30
class Project(models.Model):
       business           =models.ForeignKey(Business,on_delete=models.CASCADE,blank=True,null=True)

       project_name            =               models.CharField(max_length=100,blank=False,null=False)
       description             =               models.TextField(max_length=100, blank=False, null=False) 
       start_date              =               models.DateField()
       project_deadline        =               models.DateField()
       project_status          =               models.CharField(verbose_name='Project stage',choices=stage, max_length=200, blank=False, null=False, default='')
       project_complete_or_Inprogress=models.CharField(verbose_name='Project status', max_length=20,blank=False,null=False,choices=complete_or_Inprogress_choice)         
       client_company_name     =               models.ForeignKey(Company,on_delete=models.CASCADE)
       # contact_person          =               models.ForeignKey(ContactPerson,on_delete=models.CASCADE)
       responsible_person      =               models.ForeignKey(User,on_delete=models.CASCADE)
       estimate_Price_of_Project  =               models.IntegerField()
       reminder                =               models.DateField()
       reminder_note             =               models.TextField(max_length=100, blank=False, null=False) 
       

       class Meta():
              verbose_name_plural='Project'

       def __str__(self):
              return self.project_name



class Team(models.Model):

       project                 =               models.ForeignKey(Project, on_delete=models.CASCADE,related_name="project_link")
       project_manager=models.ForeignKey(User,on_delete=models.CASCADE)
       team_lead               =               models.ForeignKey(User,related_name='Employee', on_delete=models.CASCADE)

       def __str__(self):
              return self.project.project_name



class TeamMember(models.Model):
       team                    =             models.ForeignKey(Team, on_delete=models.CASCADE,related_name='project_link')
       team_member             =             models.ForeignKey(User, on_delete=models.CASCADE)
       def __str__(self):
              return self.team_member.email

       
class Tasks(models.Model):
       team                    =             models.ForeignKey(Team, on_delete=models.CASCADE,related_name='project_lin')

       
       member                  =               models.ForeignKey(TeamMember, on_delete=models.CASCADE,related_name='member_link')
       task_assigned           =               models.CharField(max_length=100,blank=False,default='')
       updates                  =               models.CharField(max_length=100,choices=update)
       # updates                 =               models.CharField(max_length=100,default='')
       task_deadline           =               models.DateField()
       updated_on              =               models.DateTimeField(default=datetime.datetime.now,blank=True,null=True)
       # class Meta():
       #       verbose_name_plural='Team Member'  
       
       # def __str__(self):
       #        return self.project.project_name

ProjectManagement/forms.py
from django import forms
from .models import *


stage=[ ('PLANNING','Planning'), ('DEVELOPMENT','Development'),('TESTING','Testing'),
              ('DEPLOYMENT','Deployment'),('COMPLETED','Completed')]

complete_or_Inprogress_choice=[('inprogress','INPROGRESS'),('completed','COMPLETED')]

class DateInput(forms.DateInput):
	input_type='date'

class ProjectCreationForm(forms.ModelForm):
	class Meta:
		model=Project
		fields='__all__'
		widgets={
		'start_date':DateInput(),
		'project_deadline':DateInput(),
		'reminder':DateInput()
		}
		# widgets={
		# 'project_name':forms.TextInput(attrs={'class':'form-control'}),
		# 'description':forms.TextInput(attrs={'class':'form-control ',}),
		# 'start_date':forms.TextInput(attrs={'class':'form-control'}),
		# 'project_deadline':forms.TextInput(attrs={'class':'form-control'}),
		# 'client_company_name':forms.TextInput(attrs={'class':'form-control'}),
		# 'contact_person':forms.TextInput(attrs={'class':'form-control'}),
		# # 'project_status':forms.TextInput(attrs={'class':'form-control'}),
		# # 'project_complete_or_Inprogress':forms.TextInput(attrs={'class':'form-control'})
		# }


class TeamCreationForm(forms.ModelForm):
	class Meta:
		model=Team
		fields='__all__'
		# widgets={
		# 'project_name':forms.TextInput(attrs={'class':'form-control'}),
		# 'description':forms.TextInput(attrs={'class':'form-control ',}),
		# 'start_date':forms.TextInput(attrs={'class':'form-control'}),
		# 'project_deadline':forms.TextInput(attrs={'class':'form-control'}),
		# 'client_company_name':forms.TextInput(attrs={'class':'form-control'}),
		# 'contact_person':forms.TextInput(attrs={'class':'form-control'})
		# # 'project_status':forms.ChoiceField(attrs={'class':'form-control'}),
		# # 'project_complete_or_Inprogress':forms.TextInput(attrs={'class':'form-control'})
		# }


class TeamMemberCreationForm(forms.ModelForm):
	class Meta:
		model=TeamMember
		fields='__all__'

class AllocateTaskForm(forms.ModelForm):
	class Meta:
		model=Tasks
		fields='__all__'
		widgets={
		# 'member':forms.TextInput(attrs={'class':'form-control'}),
		# 'task_assigned':forms.TextInput(attrs={'class':'form-control ',}),
		# 'updates':forms.TextInput(attrs={'class':'form-control'}),
		'task_deadline':DateInput(),
		
		}	


class Addtaskinfopage(forms.ModelForm):
	class Meta:
		model=Tasks
		fields='__all__'
		exclude=['team','member']
		widgets={
		# 'member':forms.TextInput(attrs={'class':'form-control'}),
		# 'task_assigned':forms.TextInput(attrs={'class':'form-control ',}),
		# 'updates':forms.TextInput(attrs={'class':'form-control'}),
		'task_deadline':DateInput(),
		# 'task_deadline':forms.TextInput(attrs={'class':'form-control'}),
		
		}		

ProjectManagement/templates/ProjectManagement/project.html
{% extends "crm/base.html" %}
{% load static %}
{% load bootstrap %}
{% comment %} {% bootstrap_css %}         {# Embeds Bootstrap CSS #} {% endcomment %}
{% comment %} {% bootstrap_javascript jquery='full' %} {% endcomment %}

{% block extrahead %}       {# Extra Resources Start #}
{{ form.media }}            {# Form required JS and CSS #}
{% endblock %} 

{% block content %}

<style type="text/css">
  
  label{
    font-weight: bold
  }
  .heading{
    background:#EEEEEE;
    padding: 5,
  }

  #id_description{
    max-height: 100px
  } 
   #id_reminder_note{
    max-height: 100px
  }
</style>


<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="">
              <h5 class="display-5  my-3 py-2 px-2">Add Project</h5>
    
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <hr>
                    <div class="overflow-auto">
                        <div class="form-inline">
                            <div class="form-group">
                                {# {{ent_form|bootstrap_horizontal:'col-lg-4'}}  #}
                            </div>
                        </div>
                    </div>
                    
                    <hr>
                    <div class="">
                        <input class="btn btn-primary" type="submit" name="Submit">
                    </div>
                    <hr>
                </form>
    
            </div>
        </div>
    </div>
</div>


{% endblock %}

ProjectManagement/templates/ProjectManagement/singletaskstatus.html
{% extends "crm/base.html" %}
{% load static %}
{% block title %}
    single task status
{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col">

			<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Project</th>
      <td>{{task.member.team}}</td>
   
    </tr>
    <tr>
      <th scope="row">Member</th>
      <td>{{task.member.team_member}}</td>
     
    </tr>
    <tr>
      <th scope="row">Task</th>
      <td colspan="2">{{task.task_assigned}} </td>
    </tr>
       <tr>
      <th scope="row">Status</th>
      <td colspan="2">{{task.updates}}</td>
    </tr>
       <tr>
      <th scope="row">Deadline</th>
      <td colspan="2">{{task.task_deadline}}</td>
    </tr>
 
  </tbody>
</table>

 
        <td>
        	<a class="btn btn-primary" href="{% url 'taskupdate' task.id %}">Edit</a> 
          <a class="btn btn-danger my-3" href="{% url 'taskdelete' task.id %}" >Delete</a></td>
     

  		
		</div>
	</div>
</div>
  
{% endblock content %}

ProjectManagement/templates/ProjectManagement/team.html
{% extends "crm/base.html" %}
{% load static %}
{% block title %}
Team
{% endblock title %}
{% block content %}
 <style >
    .shadowM{
    box-shadow: 2px 2px 2px 2px rgba(2,0,4,0.2);
  }

  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="text"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}


#id_project_manager{
  padding: 10px;
  margin-bottom:5px;
}
#id_team_lead{
  padding: 10px;
  margin-bottom:5px;

}
#id_project{
  padding: 10px;
  margin-bottom:5px;
  min-width: 200px;
  max-height: 200px;


}
 </style>


  <form method="POST" >
    {% csrf_token %}


  <h1 class="text-center display-5">Create New Team</h1>
      <main class="form-signin ">


      
       <div class="mb-3">

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Select Project</label><br>
              {{form.project}}

     
    </div> 

         <div class="mb-3">

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Project Manager</label><br>
                  {{form.project_manager}}

    </div> 


       <div class="mb-3">

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Team Lead</label><br>
                  {{form.team_lead}}

    </div> 


    {% for field in form %}
      <p>

        {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
        {% endfor %}
        </p>

        {% if form.non_field_errors %}
            <div style="color:red;">
              <p>{{form.non_field_errors}}</p>
            </div>
        {% endif %}

      
    {% endfor %}

  
    <button class="w-50 btn btn-lg btn-primary" type="submit">Create</button>
</main>



    
  </form>
{% endblock content %}

ProjectManagement/templates/ProjectManagement/teammember.html
{% extends "crm/base.html" %}
{% load static %}
{% block title %}
TeamMember
{% endblock title %}
{% block content %}
 <style >

     .shadowM{
    box-shadow: 2px 2px 2px 2px rgba(2,0,4,0.2);
  }

  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="text"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#id_team{
  padding: 10px;
  margin-bottom:5px;
  min-width: 200px;
  max-width: 200px;
}
#id_team_member{
  padding: 10px;
  margin-bottom:5px;

}
 </style>


  <form method="POST">
    {% csrf_token %}
  <h1 class="text-center display-5">Add TeamMember</h1>


      <main class="form-signin ">
    
         <div class="mb-3">

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Team</label><Br>
                  {{form.team}}
               

    </div> 

       <div class="mb-3">

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Team Member</label><br>
                  {{form.team_member}}

    </div> 

    {% for field in form %}
      <p>

        {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
        {% endfor %}
        </p>


      
    {% endfor %}

    <button class="w-50 btn btn-lg btn-primary" type="submit">Add</button>
</main>



    
  </form>
{% endblock content %}

ProjectManagement/templates/ProjectManagement/updateTeam.html
{% extends "crm/base.html" %}
{% load static %}
{% block title %}
Team Update
{% endblock title %}
{% block content %}
 <style >
    .shadowM{
    box-shadow: 2px 2px 2px 2px rgba(2,0,4,0.2);
  }

  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="text"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#id_project{
  padding: 10px;
  margin-bottom:5px;
}
#id_project_manager{
  padding: 10px;
  margin-bottom:5px;

}


#id_team_lead {
 padding: 10px;
  margin-bottom:5px;

}
 </style>


  <form method="POST">
  <h1 class="text-center display-1">Update Team</h1>
    {% csrf_token %}

|
      <main class="form-signin shadowM">

     

					           <div class="mb-3">

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Project</label><br>
              {{form.project}}

     
    </div> 

         <div class="mb-3">
       <label for="exampleFormControlTextarea1 " class="form-label text-left">Project Manager</label><br>
         {{form.project_manager}}
        </div> 

            <div class="mb-3">
       <label for="exampleFormControlTextarea1 " class="form-label text-left">Team Lead</label><br>
         {{form.team_lead}}
        </div> 


    {% for field in form %}
      <p>

        {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
        {% endfor %}
        </p>

        {% if form.non_field_errors %}
            <div style="color:red;">
              <p>{{form.non_field_errors}}</p>
            </div>
        {% endif %}

      
    {% endfor %}
    
    <button class="w-100 btn btn-lg btn-primary " type="submit">Update</button>
</main>



    
  </form>
{% endblock content %}

ProjectManagement/templates/ProjectManagement/updateTeamMember.html
{% extends "crm/base.html" %}
{% load static %}
{% block title %}
Team Update
{% endblock title %}
{% block content %}
 <style >

  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="text"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#id_team{
  padding: 10px;
  margin-bottom:5px;
}
#id_team_member{
  padding: 10px;
  margin-bottom:5px;

}


 </style>

<div class="container">
  <div class="row">
    <div class="col">
       <form method="POST">
    {% csrf_token %}


      <main class="form-signin ">
  <h1 class="display-5 py-5">Update Team</h1>

         <div class="mb-3">
       <label for="exampleFormControlTextarea1 " class="form-label text-left">Team</label><br>
         {{form.team}}
        </div> 

            <div class="mb-3">
       <label for="exampleFormControlTextarea1 " class="form-label text-left">Team Member</label><br>
         {{form.team_member}}
        </div> 


    {% for field in form %}
      <p>

        {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
        {% endfor %}
        </p>

        {% if form.non_field_errors %}
            <div style="color:red;">
              <p>{{form.non_field_errors}}</p>
            </div>
        {% endif %}

      
    {% endfor %}
    
    <button class="w-100 btn btn-lg btn-primary " type="submit">Update</button>
</main>



    
  </form>
    </div>
  </div>
</div>
 
{% endblock content %}

ProjectManagement/templates/ProjectManagement/updateprogress.html
{% extends "crm/base.html" %}
{% load static %}
{% block title %}

 Update Progress
{% endblock title %}
{% block content %}
 <style >

    .shadowM{
    box-shadow: 2px 2px 2px 2px rgba(2,0,4,0.2);
  }



.display-5{
  font-size: 20px;
  font-weight: 400
}


  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="text"] {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#id_project{
  padding: 10px;
  margin-bottom:5px;
}
#id_project_manager{
  padding: 10px;
  margin-bottom:5px;

}


#id_updates {
 padding: 10px;
  margin-bottom:5px;

}
 </style>


  <form method="POST" >
  <h1 class="text-center display-1"> update</h1>
    {% csrf_token %}

|
      <main class="form-signin shadowM">








              <div class="mb-3" hidden>

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Team</label><br>
                  {{form.team}}


    </div>
                 <div class="mb-3" hidden>

        <label for="exampleFormControlTextarea1 " class="form-label text-left">Member</label><br>
                  {{form.member}}


    </div>

         {% for form in form %}
          
               {% if forloop.counter >= 2 %}
                   
                  <div class="form-floating my-3" hidden>

                      {{form}}
                  <label for="floatingInput">{{form.label_tag}}</label>
                     </div>
               
               {% endif %}
             
       
                 
                {% endfor %}
                  <label for="floatingInput"><label for="id_updates">Updates:</label></label>
      <div class="form-floating my-3" >

                   {{form.updates}}
                     </div>


    {% for field in form %}

                   
      <p>

        {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
        {% endfor %}
        </p>

      

      
    {% endfor %}
    
    <button class="w-100 btn btn-lg btn-primary " type="submit">Update</button>
</main>



    
  </form>
{% endblock content %}